### ISSUE TITLE
Add a function for change the password

### ISSUE THREAD

**Issue by HRT9014** [ro-py/ro.py#80]
**Is your feature request related to a problem? Please describe.**

**If your feature is related to implementing a new Roblox API, provide information here.**
API URL: https://users.roblox.com/v1/users/{userId}
Documented: Yes/No

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jmkd3v** [comment]
Please actually fill out the bug report template 🤦
