### ISSUE TITLE
ro_py.extensions.bot fails to run

### ISSUE THREAD

**Issue by JustAnEric** [ro-py/ro.py#95]
**Describe the bug**
I get this error when I run the following code in the next section:
```
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    bot.run(os.environ.get('token'), background=True)
  File "/home/runner/RobloxBot/venv/lib/python3.10/site-packages/ro_py/extensions/bots.py", line 69, in run
    self.notifications.on_notification = self._on_notification
AttributeError: 'NoneType' object has no attribute 'on_notification'
```

**To Reproduce**
Code to reproduce the behavior:
```py
from ro_py.extensions.bots import Bot
import os,asyncio
bot = Bot()
@bot.command()
async def hello(ctx):
    await ctx.send("Hello")
bot.run(os.environ.get('token')) # this is a valid roblosecurity key/token
```

**Comment by jmkd3v** [comment]
The version of ro.py you are using (1.x) is very old and no longer supported. Newer versions of ro.py do not support chatbots or chat in general. You can try to find an older version that works (check the PyPI version history for the "ro_py" package) but we won't support those versions and they have been breaking over time. 

If you would like to update, `pip3 uninstall ro_py` and `pip3 install roblox`. Then check the docs - https://ro.py.jmk.gg/dev

**Comment by JustAnEric** [comment]
I tried this but it didnt work, anything that can help?
Plus, I followed this article, does it still work or not?
https://devforum.roblox.com/t/create-chat-command-bots-with-the-roblox-web-chat/1009508
It would be really helpful if it did.
Thanks
